V4.0 release - Restriction Pull Requests
usdot-jpo-ode/wzdx pull request #198
Opened 2021-08-24 00:49 UTC by DeraldDudley

Changes reflect...
- Making the restrictions object inheritable by the RoadEvent Object
- Changing name of LaneRestrictions to Restrictions
- Add RoadEvent-RestrictionNotice Feature
- Changed RoadRestriction to RetrictionType
- Generalized wording of Restriction Types to not specifically reference the WorkZone Events
- Changed LaneRestirctionUnit to UnitType
- Uploaded Object Model and image to reflect changes (Can copy objects from my file to master file.)
- Uploaded RoadEvent-RestrictionNotice Object Model  (Can copy objects from my file to master file.)
- Added and example

2021-08-24 14:06 UTC, j-d-b commented
@DeraldDudley Thanks for getting this started.

I will have more comments as I review each file, but at a high level:

- It seems like you addressed two issues (#178 and #175) with this PR. The restriction notice (#178) is an unrelated change to the restrictions refactoring and should be a separate PR—especially as following the spec extension meeting two weeks ago it was more clear for that to be part of a new feed.
- Following the discussion on the #175 thread and spec update co-chairs discussion, units should have been named UnitOfMeasure.
- ~~The schema needs to be updated~~ Oh I see your note on this! will do

2021-08-24 14:21 UTC, DeraldDudley commented
Curses!  I did mix the two.  Do you want me to go back and delete the "restriction notice" content or do you want to reject it?
Thoughts on how to handle the restrictions-notice feed?

2021-08-24 14:32 UTC, j-d-b commented
I think removing those changes is fine, I cloned your forked repo and was working on the schema already so I can do it.

2021-08-24 21:20 UTC, j-d-b commented on spec-content/README.md
> +[RoadEvent-RestrictionNotice](/spec-content/objects/RoadEvent-RestrictionNotice.md) | Information that describes permanent or persistant restrictions along a linear road event.
Even if `restriction-notice` EventType was added, this would still not be needed.

2021-08-25 16:06 UTC, j-d-b commented on create-feed/schemas/wzdx_v4.0_feed.json
> -          "uniqueItems": true
This is removed because it doesn't apply to objects

2021-08-25 16:19 UTC, j-d-b commented on spec-content/enumerated-types/RestrictionType.md
> +# Restriction Type
Note there is no change to the values of this enumerated type, it is just renamed from RoadRestriction to RestrictionType

2021-08-25 16:22 UTC, j-d-b commented on spec-content/objects/Restriction.md
> +# Restriction Object
This object replaces LaneRestriction (effectively a rename, with simpler property names)

2021-08-25 16:26 UTC, j-d-b approved these changes
I reviewed, made changes to the @DeraldDudley's v4.0-release-restrictions branch, re-reviewed, and now approve the changes.

I think we need another reviewer, as I originated several of the changes here and have a tendency to miss typos.

2021-08-25 16:44 UTC, j-d-b commented
The specification changes made by this PR are as follows:

- Rename **LaneRestrictionUnit** enumerated type to **UnitOfMeasurement** which allows more general use
- Rename the **RoadRestriction** enumerated type to **RestrictionType** which is more semantic
- Rename the **LaneRestriction** object to **Restriction** which allows more general use
- Remove the `lane_restriction_` prefix from the properties of the **Restriction** object
- Change `units` (on **Restriction** object) to be singular `unit`
- Change the `restrictions` array on the **RoadEvent** object to be a list of the **Restriction** object rather than a list of the **RestrictionType** (the key change from this PR: road events can now have restrictions with a value and unit)

And in addition:

- Update the example feeds to represent the specification changes above

Note that the object diagram was not updated which is the team's approach as we can't merge the diagram files so those changes need to happen after the PR is merged to the release branch. @DeraldDudley added new diagram files specific to these changes, but I removed those because we don't want those files merged in. @DeraldDudley if you have time, you can put the generated object diagram image in a comment in this thread, since you've already taken the time to make them. However, they will have to change based on the difference in the proposed changes from what you had originally.

2021-09-21 19:53 UTC, chuehlien requested changes
Nice work! Minor updates needed for `/spec-content/objects/Restriction.md` and references to the old names need to be updated in `/create-feed/README.md` (lines 31 and 87).

2021-09-21 19:53 UTC, chuehlien commented on spec-content/objects/Restriction.md
> +The Restriction object describes a restriction on a roadway or lane. This object is used by both the [RoadEvent](/spec-content/objectsRoadEvent.md) and [Lane](/spec-content/objects/Lane.md) objects.
Minor edit for line 2 (format "Restriction" for consistent styling and fix link for RoadEvent)

The `Restriction` object describes a restriction on a roadway or lane. This object is used by both the [RoadEvent](/spec-content/objects/RoadEvent.md) and [Lane](/spec-content/objects/Lane.md) objects.

2021-09-22 11:41 UTC, j-d-b commented on spec-content/objects/Restriction.md
> +The Restriction object describes a restriction on a roadway or lane. This object is used by both the [RoadEvent](/spec-content/objectsRoadEvent.md) and [Lane](/spec-content/objects/Lane.md) objects.
Thanks @chuehlien, I made the change.

2021-09-24 16:02 UTC, chuehlien commented on create-feed/README.md
> +- The [Restriction](/spec-content/objects/Restriction.md) object describes a restriction on a roadway or lane.
Thanks for updating this one @j-d-b! Heads up that Line 87 still need to be updated (RoadRestriction -> RestrictionType) for text and link. Thanks!

2021-09-28 16:46 UTC, chuehlien approved these changes
Looks great - great job @j-d-b @DeraldDudley !

2021-10-14 14:21 UTC, sknick-iastate approved these changes
Great work @DeraldDudley and @j-d-b.  

My only comment is that we should update the `restrictions` description in the [Lane object table](https://github.com/DeraldDudley/wzdx/blob/v4.0-release-restrictions/spec-content/objects/Lane.md#properties) to match either the schema that was modified to "A list of zero or more restrictions specific to the lane" or similar to the road event level restrictions description of "A list of zero or more road restrictions that apply to the roadway segment described by this road event."

2021-10-22 04:46 UTC, j-d-b commented
> My only comment is that we should update the restrictions description in the Lane object table to match either the schema that was modified to "A list of zero or more restrictions specific to the lane" or similar to the road event level restrictions description of "A list of zero or more road restrictions that apply to the roadway segment described by this road event."

@sknick-iastate I made the change.

2021-11-18 18:38 UTC, merged