Create new Worker Presence data structures
usdot-jpo-ode/wzdx pull request #206
Opened 2021-09-15 19:22 UTC by mark-mockett

This PR addresses #182 

### Summary of changes
- Add a new property `worker_presence` to the `RoadEvent` object with data type `WorkerPresence` object
- Remove `RoadEvent` property `workers_present`
- Create new `WorkerPresence` object with the following properties:
   - `are_workers_present` – Boolean
   - `source` – WorkerPresenceSource enumerated type
   - `last_confirmed_date` – string; datetime
   - `reliability_score` – Integer [0-10]
- Add the following property to the `RoadEventDataSource` object:
   - `worker_presence_definition` – array of `WorkerPresenceDefinition` type
- Add new enumerated type `WorkerPresenceSource`
- Add new enumerated type `WorkerPresenceDefinition`
- Update v4.0 JSON schema
- Update all references to `workers_present` in the examples to use new `worker_presence` and `worker_presence_definition` properties

2021-09-15 19:33 UTC, j-d-b commented
I may have missed a meeting on this because the last worker's presence meeting I attended there was not agreement on implementing it this way nor was the discussion in the issue or in person resolved. Not all comments in the issue have been addressed. I would strongly advocate for more discussion before the changes are proposed, as it is much harder to go back and change things than to do it right the first time. 

Right now it feels like mostly this just adds a lot of complexity that most members (from the meetings I attended) do not care about.

2021-09-15 19:43 UTC, j-d-b requested changes

2021-09-15 19:43 UTC, j-d-b commented on create-feed/schemas/wzdx_v4.0_feed.json
>          }
Need a comma here

2021-09-15 19:43 UTC, j-d-b commented on create-feed/schemas/wzdx_v4.0_feed.json
> +          "description": "Whether workers are present in the work zone event area, following the definition provided in the ‘worker_presence_definition’ property on the RoadEventDataSource object."
Need a comma here, and several other places. I recommend running it through a JSON validator or having a JSON language extension in your text editor which will catch these issues.

2021-09-15 19:43 UTC, j-d-b commented on spec-content/objects/RoadEventDataSource.md
> +`worker_presence_definition` | Array; \[[WorkerPresenceDefinition](/spec-content/enumerated-types/WorkerPresenceDefinition.md)\] | A list of situations in which workers are considered to be present i
I don't think the definition should be added to the road event data source because then it makes the data source specific to work zone-type road events, which conflicts with #204.

Putting the definition on the workers presence object keeps all WP stuff in one object.

2021-09-15 19:43 UTC, j-d-b commented on spec-content/objects/WorkerPresence.md
> +The `WorkerPresence` object containss information on the presence of workers in the `RoadEvent`'s area.
typo: "containss"

2021-09-15 19:43 UTC, j-d-b commented on spec-content/objects/WorkerPresence.md
> +`reliability_score` | Integer, range 0-10 | Numerical score representing the data producer’s understanding of the likelihood of workers being present in the work zone event area, with 10 indicating a
As I noted in #182 I don't like this as it is pretty much meaningless without a definition of what each number represents. If we have a definition of what each number means, then it can be an enumerated type with semantic value names, rather than numbers.

2021-10-01 17:27 UTC, mark-mockett commented on create-feed/schemas/wzdx_v4.0_feed.json
>          }
Fixed

2021-10-01 17:27 UTC, mark-mockett commented on create-feed/schemas/wzdx_v4.0_feed.json
> +          "description": "Whether workers are present in the work zone event area, following the definition provided in the ‘worker_presence_definition’ property on the RoadEventDataSource object."
Thanks for the JSON validation suggestion Jacob. Updated schema should be all fixed.

2021-10-01 17:28 UTC, mark-mockett commented on spec-content/objects/RoadEventDataSource.md
> +`worker_presence_definition` | Array; \[[WorkerPresenceDefinition](/spec-content/enumerated-types/WorkerPresenceDefinition.md)\] | A list of situations in which workers are considered to be present i
Definition moved to the WorkerPresence object.

2021-10-01 17:28 UTC, mark-mockett commented on spec-content/objects/WorkerPresence.md
> +`reliability_score` | Integer, range 0-10 | Numerical score representing the data producer’s understanding of the likelihood of workers being present in the work zone event area, with 10 indicating a
Following suggestion of Jacob and Skylar, reliability score changed to `confidence` with enumerated values of "low" "medium" and "high"

2021-10-04 20:02 UTC, j-d-b requested changes

2021-10-04 20:03 UTC, j-d-b commented on spec-content/objects/WorkerPresence.md
> +`worker_presence_last_confirmed_date` | String; [date-time](https://tools.ietf.org/html/draft-handrews-json-schema-validation-01#section-7.3.1) | Date and time at which the presence of workers was la
Or just "The date and time at which the presence of workers was last confirmed".

The `source` property description tells you what it is for, so I don't think it even needs to be mentioned here.
'

2021-11-18 18:42 UTC, merged