Business rules addition mnb
usdot-jpo-ode/wzdx pull request #259
Opened 2022-03-07 15:30 UTC by mollybehan

Updated the list of Business Rules to more accurately represent version 4.0.

2022-03-07 15:42 UTC, mark-mockett submitted a review, later dismissed
I fixed a couple typos but otherwise think this looks good!

2022-03-08 21:12 UTC, j-d-b requested changes

2022-03-08 21:12 UTC, j-d-b commented on Creating_a_WZDx_Feed.md
> +15. If provided, `bbox` must be an array of length 2n where n is the number of dimensions represented in the `geometry` property, with all axes of the most southwesterly point followed by all axes of
I think this rule should be removed as `bbox` is defined in GeoJSON so we can just lean on the GeoJSON spec to clarify how to use it, rather than having to have an explicit rule about it. Nobody uses it now and its not critical to the core of WZDx. I'd like to see these rules as minimal as possible.

2022-03-08 21:12 UTC, j-d-b commented on Creating_a_WZDx_Feed.md
> +1. The preferred [GeoJSON Geometry](https://tools.ietf.org/html/rfc7946#page-7) for a [RoadEventFeature](/spec-content/objects/RoadEventFeature.md) is `LineString`, which allows indicating the full p
Update: see below for my suggestion about a "Helpful Tips" section: this could move there.

2022-03-08 21:12 UTC, j-d-b commented on Creating_a_WZDx_Feed.md
> +13. `is_architectural_change` should be marked `true` if the road event will cause an alignment change of greater than one meter in the geometry or architecture of the underlying road segment (at the
Proposed update to clarify where the property occurs, and change from "should" to "must", to make it a hard rule:

 13. The `is_architectural_change` property on the [TypeOfWork](/spec-content/objects/TypeOfWork.md) object used by the [WorkZoneRoadEvent](/spec-content/objects/WorkZoneRoadEvent.md) must be set to `true` if the road event will cause an alignment change of greater than one meter in the geometry or architecture of the underlying road segment (at the completion of the road event). If not, it should be set to `false`.

2022-03-08 21:12 UTC, j-d-b commented on Creating_a_WZDx_Feed.md
> +12. `reduced_speed_limit_kph` only needs to be supplied if the speed limit within the road event is lower than the posted speed limit of the roadway.
Proposed update to clarify where the property occurs:

 12. The `reduced_speed_limit_kph` property on the [WorkZoneRoadEvent](/spec-content/objects/WorkZoneRoadEvent.md) only needs to be supplied if the speed limit within the road event is less than the posted speed limit of the roadway.

2022-04-27 13:13 UTC, mark-mockett requested changes
I'm feeling good about this implementation overall! I found a few minor errors and suggested some rewording/re-ordering of the business rules, but we can discuss more. 

I'll also be curious to hear others' opinions about whether the text of the business rule should be added to the spec, or only referenced with a link.

2022-04-27 13:13 UTC, mark-mockett commented on spec-content/objects/FeedInfo.md
> +`update_date` |	String; [date-time](https://tools.ietf.org/html/draft-handrews-json-schema-validation-01#section-7.3.1) | The UTC date and time when the GeoJSON file (representing the instance of the
should be BR#6

2022-04-27 13:13 UTC, mark-mockett commented on spec-content/objects/TrafficSensorLaneData.md
> +`lane_order` | Positive Integer | The lane's position in sequence within the road event (specified by `road_event_id`). The value of this property corresponds to the associated road event's [Lane](/s
I think the TrafficSensor object also has a UTC datetime reference that should have a link to BR #6

2022-04-27 13:13 UTC, mark-mockett commented on spec-content/objects/FieldDeviceCoreDetails.md
> +`data_source_id` | String | Identifies the data source from which the field device data originates. | Required | <br />Please see [Business Rule](https://user-images.githubusercontent.com/67278183/16
links are wrong in this file

2022-04-27 13:13 UTC, mark-mockett commented on spec-content/objects/RoadEventCoreDetails.md
> +`data_source_id` | String | Identifies the data source from which the road event originates. | Required | Please see [Business Rule](/Creating_a_WZDx_Feed.md#business-rules) #1.
should be BR #5

2022-04-27 19:40 UTC, mollybehan commented on Creating_a_WZDx_Feed.md
> +3. A work zone must be segmented into separate [WorkZoneRoadEvent](/spec-content/objects/WorkZoneRoadEvent.md)s when a required property of road event or lane object changes. A complex work zone shou
I resolved the first comment but I'll leave this open until we decide on the required properties vs. any property.

2022-06-07 14:08 UTC, j-d-b commented on Creating_a_WZDx_Feed.md
> +1. An event must be segmented into separate [WorkZoneRoadEvent](/spec-content/objects/WorkZoneRoadEvent.md)s, [RestrictionRoadEvent](/spec-content/objects/RestrictionRoadEvent.md)s, or [DetourRoadEve
"when a required property" should be "when the value of a required property".

`Relationship` should be lowercase.

2022-06-07 14:29 UTC, j-d-b requested changes

2022-06-07 14:29 UTC, j-d-b commented on Creating_a_WZDx_Feed.md
> +5. All times must be expressed in UTC.
Suggest changing "times" to "dates and times"

2022-06-07 14:29 UTC, j-d-b commented on spec-content/objects/DetourRoadEvent.md
> +`core_details` | [RoadEventCoreDetails](/spec-content/objects/RoadEventCoreDetails.md) | The core details of the road event that are shared by all types of road events, not specific to detours.  | Re
`<br />` element is not needed.

2022-06-07 14:29 UTC, j-d-b commented on spec-content/objects/FieldDeviceCoreDetails.md
> +`data_source_id` | String | Identifies the data source from which the field device data originates. | Required | <br />Please see [Business Rule](/Creating_a_WZDx_Feed.md#business-rules) #4.
`<br />` element is not needed.

2022-06-07 14:29 UTC, j-d-b commented on spec-content/objects/FieldDeviceCoreDetails.md
> +`update_date` | String; [date-time](https://tools.ietf.org/html/draft-handrews-json-schema-validation-01#section-7.3.1) | The UTC time and date when the field device information was updated. | Requir
`<br />` element is not needed.

2022-06-07 14:29 UTC, j-d-b commented on Creating_a_WZDx_Feed.md
>  ### WZDxFeed (Work Zones) Business Rules
Since business rules refer to the RestrictionRoadEvent which does not occur in a WZDxFeed, this section heading should be updated. I think just "Business Rules" is fine for the purpose of this PR and we can split them into feed-specific ones if needed in the future.

2022-06-07 14:32 UTC, j-d-b commented on Creating_a_WZDx_Feed.md
>  The following business rules help assure a standardized and interpretable use of the WZDx specification. The specification describes the required structure and data fields to describe a work zone, wh
Based on our meeting discussions, I think it could help to add that:

> Business rules are requirements that can not be validated by the JSON schema.

2022-06-07 19:49 UTC, mark-mockett approved these changes

2022-06-07 19:49 UTC, mark-mockett commented on spec-content/objects/Lane.md
> +`order` | Positive Integer | The position of a lane in sequence on the roadway. This value is used as an index to indicate the order of all WZDx lanes provided for a road event. | Required | Please s
I agree that that the 1-indexing should be added to the description. I'd propose this as the language for the description: "The position of a lane in sequence on the roadway. This value is used as an index to indicate the order of all lanes provided for a road event, starting with 1 for the left-most lane."

2022-06-09 18:55 UTC, mark-mockett approved these changes

2022-06-12 19:02 UTC, j-d-b approved these changes

2022-06-22 17:04 UTC, merged