Data security best practices
usdot-jpo-ode/wzdx pull request #260
Opened 2022-03-15 16:20 UTC by mollybehan

Adding Data Security content developed by the Technical Assistance Co-Chairs.

2022-03-21 14:54 UTC, mark-mockett commented on Creating_a_WZDx_Feed.md
> +All WZDx endpoints should allow only read access. No public endpoint should be exposed that allows write access to the feed.
I'd combine this with the first item (REST Endpoint Security) since they give very similar guidance

2022-03-21 16:53 UTC, j-d-b requested changes

2022-03-21 16:53 UTC, j-d-b commented on Creating_a_WZDx_Feed.md
> +All WZDx endpoints should allow only read access. No public endpoint should be exposed that allows write access to the feed.
Agree.

2022-03-21 16:53 UTC, j-d-b commented on Creating_a_WZDx_Feed.md
> +If the WZDx feed is set up as a REST Service endpoint, it is recommended that the only exposed endpoint in the REST service for the feed is a HTTP GET endpoint. If a provider will allow queries to th
In what scenario would POST be needed?

2022-03-21 16:53 UTC, j-d-b commented on Creating_a_WZDx_Feed.md
> +DOTs should consider the sources that are being used to build the WZDx feeds and ensure that those systems are also following the same best practices listed as above. WZDx feeds should be built from
Extra space (typo) between "from" and "reliable" can be removed.

2022-03-21 16:53 UTC, j-d-b commented on Creating_a_WZDx_Feed.md
> +This is a working list of best practices for standing up a WZDx data feed assembled by the Technical Assistance Co-chairs. Please note that this list is not all encompassing; DOTs should consult with
For clarity to those unfamiliar with subgroups or the WZDx process, consider changing "Technical Assistance Co-chairs" to "WZDx Technical Assistance Subgroup Co-Chairs".

2022-03-21 16:53 UTC, j-d-b commented on Creating_a_WZDx_Feed.md
> +Though all DOTs have infrastructure capabilities to host a WZDx feed, it is recommended that the feed be cloud hosted on a trusted platform due to the following reasons.
Consider ending this sentence with a colon rather than period, to signify the start of the list, and an empty line after this leading sentence.

2022-03-23 16:50 UTC, szumpf commented on Creating_a_WZDx_Feed.md
> +If the WZDx feed is set up as a REST Service endpoint, it is recommended that the only exposed endpoint in the REST service for the feed is a HTTP GET endpoint. If a provider will allow queries to th
I'm fine with the updated text.

2022-03-24 00:06 UTC, j-d-b approved these changes

2022-03-25 12:32 UTC, mark-mockett approved these changes

2022-03-25 12:39 UTC, merged