Refactor/relationship
usdot-jpo-ode/wzdx pull request #322
Opened 2022-06-03 13:49 UTC by sknick-iastate

This pull request addresses the relationship refactoring in Issue #197.

Below is a summary of the major changes for the refactoring:
- Deprecate existing relationship object
- Add new `related_road_events` object which has attributes specific for the use cases within WZDx
- Added RelatedRoadEventTypes that address various use cases within WZDx including: road event sequence, related detours/work zones, recurring work zones, and moving operations.
- Updated examples to show use of new `related_road_events` object

A summary of the new object and enumerations include:

### `related_road_events` property on the RoadEvent object (replaces `relationship`)

Property Name | Value | Description | Conformance | Notes
--- | --- | --- | --- | ---
`related_road_events` | Array; [RelatedRoadEvents](https://github.com/sknick-iastate/sknick_wzdx_spring2022/edit/refactor/relationship/spec-content/objects/RelatedRoadEvents.md) | A list describing one or more road events which are related to this road event, such as a work zone project it is part of or another road event that occurs before or after it in sequence. | Optional |

### RelatedRoadEvents Object
The RelatedRoadEvents object is used to identify another road event that is related to a road event.

Property Name | Value | Description | Conformance | Notes
--- | --- | --- | --- | ---
`type` | [RelatedRoadEventType](https://github.com/sknick-iastate/sknick_wzdx_spring2022/edit/refactor/relationship/spec-content/enumerated-types/RelatedRoadEventType.md) | The type of road event being identifed, such as another sequence of related work zones, a detour, or next road event in sequence. | Required |
`id` | String | An identifier for the related road event by the `type` property. | Required |

#### Used By
Property | Object
--- | ---
`related_road_events` | [RoadEventCoreDetails](https://github.com/sknick-iastate/sknick_wzdx_spring2022/edit/refactor/relationship/spec-content/objects/RoadEventCoreDetails.md)

### RelatedRoadEventType Enumerated Type
Describes a type of related road event, such as a work zone project, recurrent work zone, or detour-type road event. 

Value | Description
--- | ---
`first-in-sequence` | The first road event in a sequence of road events that together describe a full work zone or detour
`next-in-sequence` | The next (subsequent) road event in a sequence of road events that together describe a full work zone or detour
`first-occurrence` | The first road event of the first occurrence of a recurrent work zone. End users will need to iterate using the first road event to find all relevant road events to a related work zone
`next-occurrence` | The first road event of the next occurrence of a recurrent work zone. End users will need to iterate using the first road event to find all relevant road events to a related work zone
`related-work-zone` | First road event of related work zones (i.e. not part of a sequence of road events or recurrent work zone) that are relevant to the given road event.  End users will need to iterate using the first road event to find all relevant road events to a related work zone
`related-detour` | First road event of related detours (i.e. not part of a sequence of road events) that are relevant to the given road event.  End users will need to iterate using the first road event to find all relevant road events to a related detour
`planned-moving-operation` | First road event of a related planned moving operation work zones (i.e. not part of a sequence of road events) that are relevant to the given road event.  End users will need to iterate using the first road event to find all relevant road events to a related work zone
`active-moving-operation` | First road event of a related active moving operation work zones (i.e. not part of a sequence of road events) that are relevant to the given road event.  End users will need to iterate using the first road event to find all relevant road events to a related work zone

#### Used By
Property | Object
--- | ---
`type` | [RelatedRoadEvents](https://github.com/sknick-iastate/sknick_wzdx_spring2022/edit/refactor/relationship/spec-content/objects/RelatedRoadEvents.md)

2022-06-03 20:21 UTC, j-d-b requested changes

2022-06-03 20:21 UTC, j-d-b commented on spec-content/enumerated-types/RelatedRoadEventType.md
> +`related-detour` | First road event of related detours (i.e. not part of a sequence of road events) that are relevant to the given road event.  End users will need to iterate using the first road eve
I don't think it is clear what "the given road event" is referring to. Does it make sense to remove "that are relevant to the given road event"?

2022-06-03 20:21 UTC, j-d-b commented on examples/README.md
> +- Third work zone is a single direction, three sequential events, with detailed lane information. This work zone demonstrates the use of the `related_road_events` property, the `RelatedRoadEventTypes
It would be helpful for RelatedRoadEventType to be a link to `/spec-content/enumerated-types/RelatedRoadEventType.md`

2022-06-03 20:21 UTC, j-d-b commented on examples/WZDxFeed/scenario1_simple_linestring_example.geojson
> +                 "type": "next-road-event",
Formatting (indentation) is inconsistent here.

2022-06-03 20:21 UTC, j-d-b commented on examples/WZDxFeed/scenario3_shoulder_bidirectional_linestring_example.geojson
> +            "type": "related-work-zone",
Formatting/indentation inconsistency here too, I can run auto-format on them all if that's ok with you.

2022-06-03 20:23 UTC, j-d-b commented
/spec-content/README.md needs to be updated with the new object and enumerated type.

2022-06-06 19:05 UTC, mark-mockett reviewed
Added a couple additional comments, but once Jacob's comments are addressed I think this will be ready to go

2022-06-06 19:38 UTC, sknick-iastate commented on examples/WZDxFeed/scenario3_shoulder_bidirectional_linestring_example.geojson
> +            "type": "related-work-zone",
If you could run the auto-format that would be great.  I copied and pasted almost all of them and just changed the text so they are likely all inconsistent.

2022-06-06 20:00 UTC, sknick-iastate commented on examples/WZDxFeed/scenario4_detour_linestring_example.geojson
> +                   {
I don't remember doing that but not sure there is a good reason to (may have done this for identifying related work zones).  One possible use could be to more easily use that to select/filter the entire series of road events but I'm not sure that is enough value to add potentially unnecessary values.

2022-06-06 21:05 UTC, j-d-b commented on spec-content/enumerated-types/RelatedRoadEventType.md
> +Describes a type of relationship with a road event in relation to the road event that the RelatedRoadEvent object occurs on such as the sequence of road events along the roadway, recurrent work zone,
This description is getting more clear but is still a bit hard to read. I'm not sure RelatedRoadEventType is a "type of relationship". It is type of road event in relation to another road event. The "in relation to" is kind of weird phrasing so I'm open to other wording. Maybe an example will help.

Using `first-in-sequence` as an example: I don't interpret `first-in-sequence` as a type of relationship; it's describing a type of road event (the first road event in a sequence) with the context of the road event being referenced from (related to) another road event.

Maybe:

> Describes a type of road event from the context of another road event that it is related to.

Then the examples could be a separate sentence, starting with "For example, the sequence...".

2022-06-09 14:26 UTC, sknick-iastate commented on spec-content/enumerated-types/RelatedRoadEventType.md
> +Describes a type of relationship with a road event in relation to the road event that the RelatedRoadEvent object occurs on such as the sequence of road events along the roadway, recurrent work zone,
I think @mark-mockett didn't like having "type of road event" in the description.

What about

>Describes how a road event is related to the road event that the RelatedRoadEvent object occurs on.  For example, the sequence of road events along the roadway, recurrent work zones, nearby work zone-type road events or detour-type road events.

2022-06-12 19:15 UTC, j-d-b commented on spec-content/enumerated-types/RelatedRoadEventType.md
> +Describes a type of relationship with a road event in relation to the road event that the RelatedRoadEvent object occurs on such as the sequence of road events along the roadway, recurrent work zone,
> Describes how a road event is related to the road event that the RelatedRoadEvent object occurs on.

Nice, I like how it is explicit.

The second sentence now I think needs revision because this enumerated type describes a single related road event, but as is, the examples are describing the concepts that can be represented using multiple related road event, which I find less clear than it could be.

For example, the current second sentence example "the sequence of road events along the roadway" is not "how a road event is related to the road event that the RelatedRoadEvent object occurs on". I think more clear would be "the first or next road event in a sequence" (a single example). Here's my draft at the second sentence, which are examples to help clarify the core description.

> For example, the first road event in a sequence of events along the roadway, an instance of a recurrent work zone, or a nearby work zone-type road event.

2022-06-23 15:21 UTC, mark-mockett commented on spec-content/enumerated-types/RelatedRoadEventType.md
> +Describes a type of relationship with a road event in relation to the road event that the RelatedRoadEvent object occurs on such as the sequence of road events along the roadway, recurrent work zone,
@sknick-iastate This comment still needs to be addressed - are you good with the singular "examples" for the type description.

2022-07-08 14:52 UTC, sknick-iastate commented on spec-content/enumerated-types/RelatedRoadEventType.md
> +Describes a type of relationship with a road event in relation to the road event that the RelatedRoadEvent object occurs on such as the sequence of road events along the roadway, recurrent work zone,
@j-d-b and @mark-mockett - I modified the description and added @j-d-b change for the example.  I did leave the detour-type road event in the example sentence so it is not entirely work zone focused.

If this works for you both then I'll mark it as resolved.

2022-07-11 16:05 UTC, j-d-b commented on spec-content/enumerated-types/RelatedRoadEventType.md
> +Describes how a road event is related to the road event that the RelatedRoadEvent object occurs on. For example, the first road event in a sequence of events along the roadway, an instance of a recur
Should "events" at the end of the sentence be singular?

2022-07-14 13:44 UTC, jlarsonOmahaNE commented on examples/README.md
> +- Third work zone is a single direction, three sequential events, with detailed lane information. This work zone demonstrates the use of the `related_road_events` property, the [RelatedRoadEventTypes
I think the last sentence should be broken up into two.

2022-07-14 17:31 UTC, j-d-b commented on examples/README.md
> +- Third work zone is a single direction, three sequential events, with detailed lane information. This work zone demonstrates the use of the `related_road_events` property, the [RelatedRoadEventTypes
Agree, or a semi-color or em-dash in place of the comma.

2022-07-14 17:31 UTC, j-d-b approved these changes

2022-07-14 17:57 UTC, jlarsonOmahaNE approved these changes

2022-07-21 02:56 UTC, j-d-b commented on spec-content/objects/RelatedRoadEvent.md
> +`id` | String | An identifier for the related road event by the `type` property. The value of this property should correspond to the `id` of a RoadEventFeature within the same WZDx feed. | Required |
>  An identifier for the related road event by the `type` property.

I'm not sure what the meaning of this is.

2022-08-11 16:37 UTC, mark-mockett commented on spec-content/objects/RelatedRoadEvent.md
> +`id` | String | An identifier for the related road event by the `type` property. The value of this property should correspond to the `id` of a RoadEventFeature within the same WZDx feed. | Required |
Resolved by removing "by the type property" from the description

2022-08-11 16:37 UTC, merged