Update Examples for 4.1
usdot-jpo-ode/wzdx pull request #339
Opened 2022-09-13 15:36 UTC by sknick-iastate

This pull request updates the examples to represent the changes made for WZDx 4.1.  This includes updating both the work zone and device examples.  

In addition to updating the examples the following changes were made to the organization of the examples:
- Based on feedback from the group, an example was created for Scenario 6 of a multi-lane closure as well as Scenario 7 of a mobile work zone operation.  These examples allow for showcasing different scenarios the WZDx can be used in as well as various optional properties which can be used.
- Previously the example scenarios referred to Discussion #131 for the type of closure and traffic control.  Because this discussion is not being updated regularly it has been out of date since changes were made to the lane order.  Instead, the images are now included directly in the examples read me file and direct references to the discussion are removed from each example scenario.
- To allow for future updates, the annotated images used for the scenarios as well as the original images are located in the [images folder](https://github.com/usdot-jpo-ode/wzdx/tree/main/images).  The original images can be used if the annotations for the scenarios are out of date, no longer relevant or need additional annotations.
- Discussion #131 includes five additional scenarios that do not currently have examples (Scenarios 8-12).  The original and annotated images for these scenarios are also located in the [images folder](https://github.com/usdot-jpo-ode/wzdx/tree/main/images) in case they are added as examples in the future.

2022-09-23 20:02 UTC, sknick-iastate commented
@j-d-b and @mark-mockett - The examples should be up to date with main now after the 4.1 release

2022-10-04 16:50 UTC, j-d-b requested changes
I did a skim review and have a few initial comments. I didn't review the example files yet, which is important but time consuming.

2022-10-04 16:50 UTC, j-d-b commented on spec-content/enumerated-types/LaneStatus.md
> +This enumerated type is also used by the [RoadRestrictionFeed](https://github.com/usdot-jpo-ode/TDx/spec-content/enumerated-types/LaneStatus.md).
This should be removed/reverted here and in several files.

2022-11-21 16:31 UTC, sknick-iastate commented on Creating_a_WZDx_Feed.md
> +- Feed producers should include a completed road event with a verified start and end date in a public feed for a at least an hour or one feed refresh cycle (whichever is longer) to help inform consum
@mark-mockett and @mollybehan - Any issues with making the changes suggested by @j-d-b?

2022-11-21 16:47 UTC, mark-mockett commented on Creating_a_WZDx_Feed.md
> +- Feed producers should include a completed road event with a verified start and end date in a public feed for a at least an hour or one feed refresh cycle (whichever is longer) to help inform consum
@sknick-iastate I think the two bullets say the same thing right now (other than the proposed change) - is there supposed to be new guidance with one of these bullets?

2022-12-13 20:38 UTC, j-d-b commented on spec-content/enumerated-types/Direction.md
> +
Extra space is not needed and can be removed.

2022-12-13 20:38 UTC, j-d-b commented on spec-content/enumerated-types/LaneStatus.md
> +
Extra space is not needed and can be removed.

2022-12-13 20:48 UTC, j-d-b commented
Per co-chairs discussion 2022-12-13, local access only can be renamed "scenario 8" for consistency.

2022-12-21 17:19 UTC, jlarsonOmahaNE commented on examples/README.md
> +- Third work zone is a single direction, three sequential events, with detailed lane information. This work zone demonstrates the use of the `related_road_event` object, with [RelatedRoadEventTypes](
id 6f57aded-7291-462e-9892-607b2b7d116c in the geojson should be corrected? The next road events have workers present.

            "worker_presence": {
               "are_workers_present": false,
               "definition": [
                  "humans-in-right-of-way"
               ]
            },

2022-12-22 21:50 UTC, j-d-b requested changes

2022-12-22 21:50 UTC, j-d-b commented on examples/README.md
> +- The first road event ("id": `01841847-3cda-4aa8-a283-1b4a11f31c08`) is the planned extents of a mobile operation.  The road event uses the [RelatedRoadEventTypes](/spec-content/enumerated-types/Rel
It would be valuable to update these examples and this description to use the `work_zone_type` property that was added in 4.2.

2022-12-22 21:50 UTC, j-d-b commented on examples/README.md
> +### Scenario 7 - Mobile Operation (no examples currently)
Same comment here about removing "no examples current" since there is an example added for scenario 7

2022-12-22 21:50 UTC, j-d-b commented on examples/README.md
> +- Single work zone on a bidirectional roadwith with impact to both directions, represented by two road events ("id": `de3de57b-33fb-40e5-a6f2-a17828f82fb9`, `defbbd71-3f7e-4ddb-99de-86a48532ae57`), o
Typo: `roadwith`

2022-12-22 21:53 UTC, j-d-b commented on examples/README.md
>  The following WZDx Work Zone Feed examples represent a variety of common scenarios when creating road events. Most of the examples are modeled after work zone scenarios used in a [previous WZDx discu
Consider removing the second sentence, "Most of the examples are modeled after work zone scenarios used in a [previous WZDx discussion](https://github.com/usdot-jpo-ode/jpo-wzdx/discussions/131).", as I'm not sure the discussion is relevant any more.

2022-12-28 19:16 UTC, sknick-iastate commented on examples/README.md
>  The following WZDx Work Zone Feed examples represent a variety of common scenarios when creating road events. Most of the examples are modeled after work zone scenarios used in a [previous WZDx discu
Updates to remove the second sentence.  I still wanted to include a reference to the discussion but included it in the note below this paragraph where it mentions the images from previous examples.

2022-12-28 19:17 UTC, sknick-iastate commented on examples/README.md
> +### Scenario 6 - Multi-lane closure (no examples currently)
Removed this for scenario 6 and 7.  It was a placeholder left over before I added the examples

2022-12-28 19:18 UTC, sknick-iastate commented
> I believe there are a few duplicated images in the images folder:
> 
> * "complex_work_zone_with_ramp.png" and it's annotated version are duplicates of "sign_method.png" and its annotated verion
> * "mainline_ramp_merging_lane_closure.png" and its annotated version are duplicates of "sign_method_simple.png" and its annotated version

Resolved.  I removed the extra images and made sure we had at least one from each of the original examples.

2022-12-28 19:29 UTC, sknick-iastate commented on examples/README.md
> +- Third work zone is a single direction, three sequential events, with detailed lane information. This work zone demonstrates the use of the `related_road_event` object, with [RelatedRoadEventTypes](
I updated this to remove the `definition` since the workers present is false.  I think it was intended to include in the example the use of worker presents on different sections of the roadway so I left the other road events the same.  I did add a note in the read me about having an example with worker presences.

2022-12-30 17:42 UTC, mark-mockett commented on examples/README.md
> +![shift_work_zone](/images/lane_shift_example_annotated.png)
The image annotation doesn't match up well with the example - the example image indicates that lane 2 is closed and shoulder becomes drivable. In the example file, the shoulder is shown as "closed" and the three driving lanes have status "shift-right". 
I think the example file is the best representation if the event is represented as one event. If there were multiple events, the example file could represent where the shift begins, and the example image representation (lane 1 and 2 closed, lane 5 now of type "general") could be correct. But I still prefer the former (single event, closed shoulder, shifted travel lanes).

Possible revised annotation is below. If this looks okay, feel free to insert directly!
![lane_shift_example_annotated](https://user-images.githubusercontent.com/59966277/210098275-e67c8912-99b7-4c86-bbeb-8eb0d5dbef9f.png)

2022-12-30 19:15 UTC, mark-mockett commented on examples/README.md
> +- The first road event ("id": `01841847-3cda-4aa8-a283-1b4a11f31c08`) is the planned extents of a mobile operation.  The road event uses the [RelatedRoadEventTypes](/spec-content/enumerated-types/Rel
```suggestion
- The first road event ("id": `01841847-3cda-4aa8-a283-1b4a11f31c08`) is the planned extent of a mobile operation.  The road event uses the [RelatedRoadEventType](/spec-content/enumerated-types/RelatedRoadEventType.md) value of `active-moving-operation` to relate to the active road event of the mobile operation. This road event also uses the `work_zone_type` of `planned-moving-area` to indicate it is the planned extents of a moving operation.
```

A couple typos to fix in this description

2022-12-30 19:16 UTC, mark-mockett commented on examples/README.md
> +- The second road event ("id": `71a97769-6c61-41a8-bbfd-0d84e0d073e6`) is the active extents of a mobile operation.  This represents the current location of the mobile operation and is expected to mo
```suggestion
- The second road event ("id": `71a97769-6c61-41a8-bbfd-0d84e0d073e6`) is the active extent of a mobile operation.  This represents the current location of the mobile operation and is expected to move as the mobile operation changes locations.  The road event uses the [RelatedRoadEventType](/spec-content/enumerated-types/RelatedRoadEventType.md) value of `planned-moving-operation` to relate to the planned extent road event of the mobile operation. This road event also uses the `work_zone_type` of `moving` to indicate it is a road event that is actively moving.
```

2022-12-30 19:27 UTC, mark-mockett commented on examples/WorkZoneFeed/scenario7_mobileoperation_linestring_example.geojson
> +        "update_date": "2020-06-18T14:37:31Z"
```suggestion
        "update_date": "2022-09-13T15:17:13Z"
```

Suggest updating the feed dates to align with the more recent events - suggested time is 5 seconds after the moving road event's update date.

2022-12-30 19:27 UTC, mark-mockett commented on examples/WorkZoneFeed/scenario7_mobileoperation_linestring_example.geojson
> +    "update_date": "2020-06-18T15:00:00Z",
```suggestion
    "update_date": "2022-09-13T15:17:13Z",
```

2022-12-30 19:33 UTC, mark-mockett commented on examples/README.md
> +The [Scenario 2 Example](/examples/WorkZoneFeed/scenario2_laneshift_linestring_example.geojson) is based on the annotated image below which keeps all lanes open but shifts them resulting in both shou
```suggestion
The [Scenario 2 Example](/examples/WorkZoneFeed/scenario2_laneshift_linestring_example.geojson) is based on the annotated image below which keeps all lanes open but shifts them resulting in both shoulders being closed on a multi-lane facility. The image below also includes annotations in red identifying the road event extent lane numbering (the actual geojson examples may differ slightly to show various examples of this type of closure).
```
Suggested wording change to accompany suggested image change below

2022-12-30 19:38 UTC, mark-mockett requested changes
Left individual comments along the way, but I noted a few items that should be updated:

- [x] Update image for Example 2 to show only one road event with lanes 1 and 5 closed and lanes 2-4 shifted right
- [x] Fix typos in descriptions of scenario 7
- [ ] Update feed-level dates in scenario 7 file
- [ ] Update versions of all scenarios to 4.2

@sknick-iastate let me know if you'd like me to commit any of these changes once you've seen the suggestions!

2023-01-03 15:18 UTC, sknick-iastate commented on examples/README.md
> +![shift_work_zone](/images/lane_shift_example_annotated.png)
I agree and have this updated.

2023-01-13 20:31 UTC, mark-mockett approved these changes
Just pushed a commit to fix the last two version numbers in example files, which resolves all my comments! thanks @sknick-iastate for spearheading this

2023-01-20 19:19 UTC, jlarsonOmahaNE approved these changes

2023-01-31 14:04 UTC, j-d-b approved these changes

2023-01-31 14:05 UTC, j-d-b commented
Sorry for the delay here, thank you @sknick-iastate for creating this PR.

2023-01-31 14:29 UTC, merged