Mobile work zone
usdot-jpo-ode/wzdx pull request #351
Opened 2022-10-19 17:01 UTC by sknick-iastate

This pull request address the mobile work zone issue #125. 

During the 4.1 release, a mobile work zone related road event option was added but didn't resolve the original issue of being able to identify a mobile work zone independently.  The proposed changes adds an optional `work_zone_type` property to the [WorkZoneRoadEvent](https://github.com/usdot-jpo-ode/wzdx/blob/main/spec-content/objects/WorkZoneRoadEvent.md) object.  This property will have the ability to identify if the work zone is static, moving, or a planned moving operation.  If other work zone types which impact the operation of the work zone are identified in the future they can be added to this property.

At this point, the co-chairs recommend that this be a required property during the next major release.  For now it will be an optional property to avoid breaking backwards compatibility.

A summary of the new object and enumerations include:

# WorkZoneRoadEvent Object

### New Property
Name | Type | Description | Conformance
--- | --- | --- | ---
`work_zone_type` | [WorkZoneType](/spec-content/enumerated-types/WorkZoneType.md) | The type of work zone road event | Optional | 

# WorkZoneType Enumerated Type
The type of work zone road event

## Values
Value | Description
--- | ---
`static` | The road event statically placed - not moving.
`moving` | The road event is actively moving on the roadway. As opposed to `planned-moving-area`, the road event goemetry changes at the operation moves.
`planned-moving-area` | The planned extent of a moving oepration.  The active work area will be somewhere within this road event.  As opposed to `moving`, the road event geometry typically does not actively change

## Used By
Property | Object
--- | ---
`work_zone_type` | [WorkZoneRoadEvent](/spec-content/objects/WorkZoneRoadEvent.md)

2022-10-21 14:15 UTC, j-d-b requested changes

2022-11-17 22:05 UTC, mark-mockett approved these changes
Merge release/v4.2 back in to this branch once more to clean up the changes, but then should be good to go.

2022-11-18 13:13 UTC, j-d-b commented
I am waiting for the merge conflicts to be resolved to approve, but the implementation looks good.

2022-11-18 15:15 UTC, j-d-b approved these changes

2022-12-13 20:05 UTC, merged